name: web_communication
description:
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  intl: any
  meta: any
  logging: any
  logger: any

  synchronized: any

  pshondation:
    git:
      url: https://github.com/pshonkaaa/package.pshondation.dart.git

  web_chrome_api:
    git:
      url: https://github.com/pshonkaaa/package.web_chrome_api.web.dart.git
  